imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de
    app.path.images: /uploads/images

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        jsqueeze: ~

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

vich_uploader:
    db_driver: orm
    mappings:
        images:
            uri_prefix: '%app.path.images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images'

easy_admin:
    site_name: "Autonome Schule Schaffhausen"
    design:
        brand_color: "#e7453a"
        menu:
            - { entity: Homepage, 'icon': 'home' }
            - { entity: Slider, 'icon': 'picture-o' }
            - { entity: Goal, 'icon': 'star' }
            - { entity: Event, 'icon': 'calendar' }
    list:
        max_results: 50
    show:
        max_results: 20
    formats:
        date: 'd.m.Y'
        time: 'H:i'
        datetime: 'd.m.Y H:i'
    entities:
        Homepage:
            class: AppBundle\Entity\Homepage
            help: 'Einträge für die Homepage, mögliche Werte für das Icon: "/icon/crew.png", "/icon/group.png", "/icon/hands.png", "/icon/together.png"'
        Slider:
            class: AppBundle\Entity\Slider
            help: 'Einträge für den Slider'
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
        Goal:
            class: AppBundle\Entity\Goal
            help: 'Einträge für die Ziele, mögliche Werte für das Icon: "/icon/crew.png", "/icon/group.png", "/icon/hands.png", "/icon/together.png"'
        Event:
            class: AppBundle\Entity\Event
            help: 'Einträge für Events'
